name: Publish to npm

on:
  push:
    branches: [main]
    paths:
      - 'package.json'
  workflow_dispatch: # This adds a manual "Run workflow" button in the GitHub UI!

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - run: pnpm run build --if-present

      - name: Publish
        run: pnpm publish --no-git-checks --access public --provenance
